# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md", "Gemfile", "Gemfile.lock"] # files to exclude
markdown: kramdown
highlighter: rouge

title: Ashish Madeti
description: Stylish Jekyll Theme
author:
  name: Ashish Madeti
  email: ashishmadeti@gmail.com
  github: ashishmadeti
  twitter: false
  pinterest: false
  linkedin: ashishmadeti
  bio: Student, KDE Contributor
  email_md5: 3981a429861d323c19f296dafc3d1f1d

rss_path: feed.xml
archives_path: archives.html
tags_path: tags.html

#BASE_PATH: http://ashishmadeti.github.io/dbyll

# All links will be namespaced by BASE_PATH if defined.
# Links in your website should always be prefixed with {{ site.BASE_PATH }}
# Do not put a "/" at the end of the url.
#
# CNAME (http://yourcustomdomain.com)
#   DO NOT SET BASE_PATH JUST LEAVE IT BLANK 
#   (urls will be prefixed with "/" and work relatively)
#
# GitHub Pages (http://username.github.io)
#   DO NOT SET BASE_PATH JUST LEAVE IT BLANK 
#   (urls will be prefixed with "/" and work relatively)
#
# GitHub Project Pages (http://username.github.io/project-name)
#  A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
#  REQUIRED! Set BASE_PATH to "http://username.github.io/project-name"
